- name: demo on shell
  hosts: all
  tasks:
    - name: Running the uptime
      ansible.builtin.shell: uptime
      register: result

    - name: Printing the uptime 
      ansible.builtin.debug:
        msg: "{{result.stdout}}"

    - name: declaring the variable
      set_fact:
        EXITCODE: "{{result.rc}}"

    - name: Printing the exit code
      ansible.builtin.debug:
        msg: "The exit code of the command is {{EXITCODE}}"