- name: demo on shell
  hosts: all
  tasks:
    - name: Running the uptime
      ansible.builtin.shell: uptime
      register: result

    - name: Printing the uptime 
      ansible.builtin.debug:
        msg: "{{result}}"